import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import packageJson from "../package.json";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex h-14 w-full items-center justify-between border-b border-black/[.08] bg-white px-6 text-sm dark:border-white/[.145] dark:bg-black sm:px-10">
          <Link
            className="font-semibold text-foreground transition-colors hover:text-zinc-600 dark:hover:text-zinc-300"
            href="/"
          >
            tfsystem-web-framework
          </Link>
          <div className="flex items-center gap-4">
            <a
              aria-label="GitHub repository"
              className="text-foreground transition-colors hover:text-zinc-600 dark:hover:text-zinc-300"
              href="https://github.com/tfsystem/tfsystem-web-framework"
              rel="noopener noreferrer"
              target="_blank"
            >
              <svg
                aria-hidden="true"
                className="h-5 w-5"
                fill="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  clipRule="evenodd"
                  d="M12 2C6.477 2 2 6.484 2 12.021c0 4.428 2.865 8.184 6.839 9.504.5.092.682-.217.682-.483 0-.237-.009-.868-.014-1.703-2.782.605-3.369-1.343-3.369-1.343-.455-1.158-1.11-1.467-1.11-1.467-.908-.621.069-.608.069-.608 1.004.07 1.532 1.032 1.532 1.032.892 1.53 2.341 1.088 2.91.832.091-.647.35-1.088.636-1.338-2.221-.253-4.555-1.113-4.555-4.951 0-1.094.39-1.987 1.03-2.687-.103-.254-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.56 9.56 0 0 1 12 6.85a9.56 9.56 0 0 1 2.504.337c1.909-1.296 2.748-1.026 2.748-1.026.546 1.378.203 2.396.1 2.65.64.7 1.028 1.593 1.028 2.687 0 3.848-2.337 4.695-4.566 4.943.359.31.678.921.678 1.856 0 1.339-.012 2.419-.012 2.748 0 .268.18.58.688.482A10.025 10.025 0 0 0 22 12.021C22 6.484 17.523 2 12 2Z"
                  fillRule="evenodd"
                />
              </svg>
            </a>
            <span className="font-mono text-xs text-zinc-600 dark:text-zinc-400">
              v{packageJson.version}
            </span>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
